name: testing
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.6.9
    - dataclasses
    - neovim
    - numpy
    - pip
    - pytorch
    - torchvision
    - tqdm
    - pip:
        - pytorch-lightning
        - requests
        - tensorboard
